# Generated by Django 5.0.6 on 2024-07-18 06:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_chatrooms_private_chatrooms_banned_member_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrooms',
            name='banned_member',
            field=models.ManyToManyField(blank=True, editable=False, related_name='banned_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatrooms',
            name='current_member',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='chatrooms',
            name='members',
            field=models.ManyToManyField(blank=True, editable=False, related_name='member_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
