# Generated by Django 5.0.6 on 2024-07-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_chatrooms_total_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrooms',
            name='current_member',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
